### ISSUE TITLE
Original dataset from NeRF or my own dataset

### ISSUE THREAD

**Issue by jdiazram** [airalcorn2/pytorch-nerf#2]
Hi, excellent work with this code of NeRF. I have a question, can I use the original dataset of NeRF or my own dataset using generate_nerf_dataset.py to create them?

thx

**Comment by airalcorn2** [comment]
Thanks for the kind words. I have a notebook [here](https://colab.research.google.com/drive/1MY6pk3vY7rrYal8oS6_s7zTkGN9lkHQr?usp=sharing) demonstrating how to use my code to train a tiny NeRF model on the `tiny_nerf_data.npz` file used by the original NeRF authors in their notebook [here](https://colab.research.google.com/github/bmild/nerf/blob/master/tiny_nerf.ipynb). The only differences from my [`run_tiny_nerf.ipynb`](https://colab.research.google.com/drive/1ntlbzQ121-E1BSa5EKvAyai6SMG4cylj?usp=sharing) notebook are that:

1) I do not divide `data["images"]` by 255 because the images have already been normalized to be between zero and one.
2) I calculate `camera_distance` from the pose array, i.e., `camera_distance = float(np.linalg.norm(data["poses"][0, :3, -1]))`.
3) I set `t_n`, `t_f`, and `N_c` to 2.0, 6.0, and 64, respectively, to follow the choices used in the original NeRF authors' notebook above.

For the following test view from the original NeRF authors' notebook:

![download](https://user-images.githubusercontent.com/1927770/176674162-66784169-6733-4d74-824b-6778bfd8760a.png)

my notebook generated the following after 14,900 iterations (~45 minutes on a P100 GPU):

![download](https://user-images.githubusercontent.com/1927770/176682514-173e6655-807f-4737-8148-61f6c07f3f96.png)
