### ISSUE TITLE
A question about "get_image_features_for_query_points" in "run_pixelnerf.py"

### ISSUE THREAD

**Issue by kunkun0w0** [airalcorn2/pytorch-nerf#3]
Hi~ thanks for your clear reproduction! 
However, I still confuse about **how to query the image feature for the points along the target rays**.

https://github.com/airalcorn2/pytorch-nerf/blob/a6e1e92e97d4686a4cabd7f02fcbb6350b8e59d4/run_pixelnerf.py#L50-L70

I notice that **the z-value of the points is based on the world coordinate not the camera coordinate.**
So directly adopting the projection in L53 seems not reasonable according to your reference.
If I was wrong, please let me know! Thanks!

**Comment by airalcorn2** [comment]
The scene is organized such that the object is centered at the origin and [the camera is located at `(0, 0, camera_distance)`](https://github.com/airalcorn2/pytorch-nerf/blob/master/pixelnerf_dataset.py#L44), regardless of what the initial viewpoint is. To get the NeRF rays, [the ray origins and directions are first rotated](https://github.com/airalcorn2/pytorch-nerf/blob/master/run_pixelnerf.py#L326-L328) and then marched accordingly, i.e., both the camera coordinates and the ray coordinates are in world space. That's why the projection is `1 / (camera_distance - z)`.

**Comment by kunkun0w0** [comment]
My carelessness.
Thanks for your clear explanation!
